apiVersion: apps/v1
kind: Deployment
metadata:
  name: diggums
spec:
  selector:
    matchLabels:
      app: diggums
  replicas: 2
  template:
    metadata:
      labels:
        app: diggums
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
